name: Lint and Typecheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      # Set up pnpm
      - uses: pnpm/action-setup@v3

      # Set up Node.js with caching for pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # Check out the code
      - uses: actions/checkout@v4

      # Install dependencies
      - shell: bash
        run: pnpm install

      # Run lint and typecheck
      - name: Run lint
        shell: bash
        run: pnpm lint

      - name: Run typecheck
        shell: bash
        run: pnpm typecheck
